### ISSUE TITLE
Vercel Link Doesn't Work

### ISSUE THREAD

**Issue by imcodingideas** [redwoodjs/bighorn-website#34]
Taking a look around and I noticed [bighorn.vercel.app](https://bighorn.vercel.app/) doesn't work. I guess that's why your building a hosting platform. haha. Just kidding.

**Comment by Josh-Walker-GM** [comment]
Haha thanks for pointing this out! This was an older link that is no longer live. We'll probably update it to point to the live site: https://redwoodjs.com but we have a few DNS things to work out before we do.

In the meantime https://bighorn-website.fly.dev/ should be the best link to follow to the deployed site.
