### ISSUE TITLE
Youtube embeds are not the correct height/width

### ISSUE THREAD

**Issue by Josh-Walker-GM** [redwoodjs/bighorn-website#46]
After updating to use mdx within the repo this broke. Example shown below.

<img width="1250" alt="image" src="https://github.com/user-attachments/assets/70705a15-f897-4134-bc22-d5d942252ced">

You can also see there is not sufficient padding/margin at the bottom of the embed either.

**Comment by ahaywood** [comment]
@Josh-Walker-GM I'm blocked on this ... would you mind taking a look? I recorded a Loom video, explaining (also sorry about the audio, I used my built-in mic)

https://www.loom.com/share/5f2195bfad0f4aa1abd008aa6d15ddf8

**Comment by Josh-Walker-GM** [comment]
I think we can mark this one done after #70
